title: "Curso Javascript Fullstack"
remote_theme: pmarsceill/just-the-docs
logo: "https://res.cloudinary.com/boolean-spa/image/upload/v1620151848/boolean-academia-logo_km16h3.png"
aux_links:
  "Academia":
    - "https://boolean.cl"
  "Empresas":
    - "https://boolean.cl/services"

aux_links_new_tab: true
